[project]
name = "EtuUTT-Bot"
license = "MIT"
requires-python = ">=3.8"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "RET", "SIM", "PT", "RUF", "T20", "ERA", "INP"]
ignore = ["E501"]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff]
line-length = 99

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"
